canonical/snapd-desktop-integration

src/main.c
This PR cleans up the use of notifications, partly based on the feedback in #6.  In particular:
1. If the "Some required theme snaps are missing" notification is visible and we see another theme change, don't pop up a second notification. We use the `NotifyNotification::closed` signal to track when the notification has been closed, so a new notification can be presented if necessary.
2. Present the installation status notification as an update of the "Installing missing theme snaps" notification, so users don't end up with both notifications visible at once.
I haven't adopted the suggestion to use the GIO notifications API, since that does not currently work with snaps: it requires a D-Bus activatable desktop file, which is incompatible with the desktop file naming snapd currently uses. …
=> Don't pop up duplicate notifications

src/ds_state.h, src/main.c, src/refresh_status.c
This MR keeps track of the snaps that have a refresh popup, to avoid showing more than one.
=> DT-576: don't duplicate refresh popups

src/refresh_status.c
When the timer checks the file content and decides to destroy the window, it can happens that the timer function can be called twice before the window is really destroyed. This can result in a double-free bug.
To avoid that, this MR removes the timer callback in that case.
=> Fix timer bug

snap/snapcraft.yaml, src/main.c
In some cases, like when connecting from a remote terminal using SSH, GTK can't be initialized and fails. In that case, this daemon keeps being relaunched over and over.
This patch fixes it by checking first if it is possible to initialize GTK, and only relaunching the daemon if there was an error.
Fix https://github.com/snapcore/snapd-desktop-integration/issues/14
=> Don't restart if DISPLAY is not set

src/dbus.c, src/dbus.h, src/ds_state.h, src/main.c, src/refresh_status.c, src/refresh_status.h
Currently, snapd-desktop-integration uses an odd mix of glib mainloop and pieces of GTK. This must be updated to use GtkApplication, in order to do a future full migration into Gtk4.
=> DT-719: Migrate into GtkApplication

src/main.c
When a gtk-theme snap is missing, snapd-desktop-integration shows a notification allowing to install it. Unfortunately, when that notification is moved to the list of "old" notifications, it stops reacting.
The reason is that when a notification in that list is clicked, the program that created it receives a 'default' action, while the two actions defined in the notification are 'yes' and 'no'.
This patch adds a 'default' action that also installs the snap.
Fix https://github.com/snapcore/snapd-desktop-integration/issues/13
=> DT-774: install required theme snap on notification click

src/main.c
If a gtk-theme snap is missing and snapd-desktop-integration offers the user to install it, the user clicks on "yes" and then it cancels the process (for example, when asked by the root password), the error message is meaninless: it just says "failed".
This patch fixes this, and puts the basic infraestructure to show more specific errors on other cases.
Fix https://github.com/snapcore/snapd-desktop-integration/issues/13
=> DT-775: show a meaningful message on error

data/io.snapcraft.SnapDesktopIntegration.dbus.xml, src/dbus.c, src/refresh_status.c, src/refresh_status.h
This MR adds two new DBus methods that allow to set a percentage value in the progress bar, or set again the pulsing bar.
This will be useful to give to the user more info about how the snap download is going.
=> DT-954: add percentage support

.github/workflows/format.yaml, src/dbus.c, src/dbus.h, src/ds_state.h, src/main.c, src/refresh_status.c, src/refresh_status.h
Enforce a code style by formatting using clang-format. This ensures all contributions are in the same style and reduces time to write code (just run clang-format -i after making changes).
=> Enforce a code style

README.md, data/resources/snap_is_being_refreshed.ui, meson.build, po/es.po, po/oc.po, po/snapd-desktop-integration.pot, snap/snapcraft.yaml, src/dbus.c, src/ds_state.h, src/refresh_status.c, src/refresh_status.h
Allows to specify several extra options in the "extra_data" field in each DBus call. These options allow to set an icon, change the window's title, or the message.
In order to get access to any SNAP icon, it requires a "system-files" interface and permissions, which, for the snap store, requires specific permissions https://snapcraft.io/docs/system-files-interface
=> Add extra options

snap/snapcraft.yaml
Replace the launch interface with the system-files one, as requested.
=> Use system-files interface

data/resources/snap_is_being_refreshed.ui, src/refresh_status.c, src/refresh_status.h
This MR makes the window bigger if the text requires more space, but once it has grown, it will keep the new size, no matter if new texts are smaller. This avoids the ugly effect of a window increasing and decreasing its size.
=> Make the window bigger if needed, but not smaller

src/refresh_status.c
By default the icon should be not visible, but when it is set, it must be changed to "visible". The previous patch made it invisible by default, but didn't make it visible when it is set. This patch fixes this.
=> Ensure that the icon is visible only when set

data/resources/sdi-refresh-dialog.ui, src/sdi-refresh-dialog.c
Before:
After:
Title is fixed in https://github.com/snapcore/snapd-desktop-integration/pull/66
=> Fix alignment issues in refresh dialog, use clearer names for widgets.

src/sdi-helpers.c, src/sdi-refresh-monitor.c
If an event is in HOLD state, hide any progress bar for it and avoid checking it over and over again.
Also, remove several NULL warnings.
=> Extra fixes

meson.build
Several changes done in snapd-desktop-integration now requires some extra API methods from snapd-glib. This PR updates the required version.
=> Require last version of snapd-glib

README.md, meson.build, meson_options.txt, src/main.c, src/sdi-notify.c
Due to the fact that snap doesn't set a .desktop file for the snaps with the original name, but builds one with snap-name_app-name.desktop, the desktop identification usually fails. This makes GNotify to not be able to identify the .desktop file and set the right icon in the top-left corner of the notifications it sends.
This patch migrates the notification code to libnotify, which allows to bypass this problem. But the original code is kept  inside an #ifdef to allow to revert to it in the future, when this problem is fixed in snapd.
=> Udeng-2978: put the right icon in the top left corner

data/io.snapcraft.PrivilegedDesktopLauncher.dbus.xml, data/meson.build, snap/snapcraft.yaml, src/meson.build, src/sdi-helpers.c, src/sdi-helpers.h, src/sdi-notify.c, src/sdi-refresh-monitor.c
The UX team asked for allowing to launch the store directly from a pending refresh notification, to allow the user to see what snaps are pending. Also recommended a change in the text of the other button in the notifications.
EDIT: now it also launches the updated snap when clicking in the "Snap is updated" notification.
=> Launch the store from refresh notification

src/sdi-refresh-monitor.c
When calling foreach in the dictionary, g_object_ref() is called once on self, but in the callback it is assigned to a g_autoptr in each call. If there is only one entry in the dictionary, it works, but if there are several, the second time the callback is called, self will be freed again, and the program crashes.
=> Fix crash when showing several progress bars

src/sdi-refresh-monitor.c
Sometimes, an incorrect value with the number of tasks is sent, and the progress bar shows an odd appearance. This patch fixes it.
=> Fix odd progress bar

src/sdi-refresh-monitor.c
When a change is processed, a timeout is set to continue monitoring it. Unfortunately, when a change is sent again to the program, a new timeout is set, thus having two "pseudothreads" monitoring the same change.
This patch checks if there is already a timeout for a change, and avoids creating a new timeout in that case, because the current one will already manage new changes.
=> Don't launch several "threads" for same change

src/sdi-refresh-monitor.c
When a refresh was cancelled (for example, because the snap was launched before it has completed the refresh), the snap is reverted, but the current code fails to detect correctly this, and snapd-desktop-integration could be left in an invalid state, asking for already completed changes over and over again.
This patch fixes this bug.
=> Fix cancelled refreshes

src/sdi-notify.c
When a notification with pending updates is shown, clicking on it should open the store with the available updates.
=> Show updates when clicking on notification

tests/test-snapd-desktop-integration.c
The tests folder contains a test for theme installation, but it fails.
This patch fixes it.
=> Fix theme tests

src/main.c
* Clean exit
This patch manages the INT and TERM signals to cleanly quit the main loop and free all the used resources.
* Clear objects in shutdown event
=> Clean exit (#98)

src/sdi-helpers.c, src/sdi-helpers.h, src/sdi-notify.c, src/sdi-refresh-monitor.c
Several helper functions were used only in a single .c file, thus being "fake helpers". This PR moves them into their corresponding file, makes them static to avoid exporting them, and removes the `sdi_` prefix.
=> Move false helpers where they are used

.clang-format, src/sdi-notify.c, src/sdi-refresh-dialog.c, src/sdi-refresh-monitor.c
Adds a clang-format option to remove empty lines at the beginning of blocks.
=> Remove empty lines at the beginning of blocks

src/main.c, src/sdi-forced-refresh-time-constants.h, src/sdi-notify.c, src/sdi-notify.h, src/sdi-refresh-monitor.c, src/sdi-refresh-monitor.h, tests/data/icon1.svg, tests/data/meson.build, tests/meson.build, tests/test-sdi-notify.c
This PR does some refactoring on the `sdi-notify` object to allow to be connected through signals to the `sdi-refresh-monitor` object (mainly replace the GSList with the list of applications that have available refreshes, with a GListModel, a GObject with the same functionality, which is easier to send through signals). It also moves the little function that checks if a refresh is or not forced, from the `notify` object into the `monitor` object, thus ensuring that the `notify` object is just as "dumb" as possible about the refresh process.
This change not only decouples more the code between the refresh monitor and the notifications object; it also allows to add ten unitary tests for the notifications code (although they can't be run automatically because they require to connect to the …
=> Refactor notifications and add unitary tests

tests/mock-snapd.c, tests/test-sdi-notices-monitor.c
There was a little memory leak in the unitary test.
=> Fix memory leak in unitary test

tests/mock-snapd.c, tests/mock-snapd.h
This patch just updates mock-snapd to the last version, which adds support for the "after" parameter in the "notices" call.
=> Update mock-snapd to the last version

meson.build
Adds a check to ensure that at least meson 0.64.0 or later is used, since it is required for fs.copyfile.
=> Add meson_version to meson.build

src/sdi-refresh-dialog.c
When no text is specified for a progress bar, NULL is passed to gtk_progress_bar_set_text(). Unfortunately, this shows the text (NULL) instead of leaving it blank.
This patch fixes this.
=> Fix NULL text in progress bar

.github/workflows/unitary-test.yaml, tests/test-snapd-desktop-integration.c, tests/weston-test-theme-change.ini
This PR runs the `test-snapd-desktop-integration` (theme-change test) in the CI.
=> Use weston to test theme changes in CI

src/sdi-refresh-monitor.c
The 'Abort' state is also used when an operation has been cancelled.
=> Add missing state

.github/workflows/tics.yaml, .github/workflows/unitary-test.yaml
This patch uses a different CI/CD workflow to generate the coverage data and upload it to tiobe.
=> Add TICS workflow for CI/CD

tests/launch-weston-test-theme-change.sh, tests/weston-test-theme-change.ini
When launching the theme-change test, it is done through Weston window manager, because it requires it. Unfortunately, if the test fails and returns a non-zero value, Weston doesn't propagate it, so it always returns a zero, thus cheating the CI/CD pipeline and making it believe that the test passed.
This patch fixes this by checking the return value of the test and sending a SIGKILL to Weston if the test failed; this makes Weston to return a non-zero value, thus notifying to the CI/CD pipeline that the test failed.
=> Fix theme change test

coverage_base/cobertura-notify.xml, coverage_base/cobertura-progress-window.xml, gcovr.cfg
This patch adds coverage to the tests files themselves.
The key part is in the gcovr.cfg file, where the tests folder is added. Of course, the pre-built coverage files had to be rebuilt.
=> Add tests coverage

.github/workflows/tics.yaml, src/sdi-refresh-monitor.c
When a sdi-refresh-monitor object is destroyed, there could remain some g_timeout_once() sources. This patch ensures that they are clean up.
=> Remove timeout source on destroy

src/sdi-snapd-client-factory.c
Snapd has changed to an abstract socket when used from inside a snap, so a change was required in snapd-glib. Now, the library automagically detects if it is inside a snap and chooses, in that case, the new abstract socket if it exists, or the old, normal socket if the abstract doesn't exist, so the current code to set the socket if we are inside a snap is not only not needed anymore, but it will stop working in the next snapd version, so it must be removed and let snapd-glib to choose the right socket.
=> Add support for snapd abstract socket

.github/workflows/format.yaml
The ubuntu 20.04 actions runner is being deprecated, so we must update it to a more recent one.
https://github.com/actions/runner-images/issues/11101
=> Update ubuntu version in test

src/sdi-notify.c, src/sdi-theme-monitor.c, tests/test-snapd-desktop-integration.c
Ubuntu Budgie has a bug in its notifications system: when the user clicks on an action (for example, "Yes" for installing new themes from the Snap Store), it sends the button action (thus, "yes" action), but after that also sends the default action. Instead, both Gnome and KDE only sends the button action.
This results in odd behavior in this system: since the default action does the same than the "yes" action, if the user presses "Yes", two install processes will run concurrently, conflicting between them and resulting in an installation error shown (due to one of the processes being unable to install the themes), while, at the same time, the themes are correctly installed (by the second process).
Also, if the user presses "No", the "no" action is just ignored and nothing is done; but …
=> Add a workaround for Ubuntu Budgie
